### ISSUE TITLE
Quarry: Chunk loading issue

### ISSUE THREAD

**Issue by HexyWitch** [alex-lawson/sb-automation#136]
Gonna need a way to load chunks for this. Destroying tiles seems to work, but when it tries to go down the hole a second time after digging the chunk doesn't load and it comes back.

**Comment by silentstormpt** [comment]
Using a timestamp to save up the time it started working will help saving all the blocks that were destroyed during the current time and the last timestamp (same solution the farm modder had)

**Comment by alex-lawson** [comment]
Saving the time and then trying to catch up to the current state is probably not going to be possible, since it would then have to destroy a lot of blocks at once, causing major lag (and other potential problems). The main issue is how to cleanly resume the process after some part of the machine is unloaded and reloaded. We should probably avoid drilling into unloaded chunks until we have a solution for this, as long as it doesn't reduce the functionality of the quarry too much.

**Comment by alex-lawson** [comment]
Chunk loading will be in a future patch, so we can use that when it's available.
